excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://annebione.github.io
title: Anne Bione 
tagline: Engenharia de software. UX. JavaScript. Projetos. Política.
description: Funkeira emo do samba, da poesia, do Sport. Cozinheira de chips e fios e grafiteira de kani. Tudo isso, mas nunca o bastante. Tipicamente paulistana, mas do Recife.
paginate: 5
