excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://annebione.github.io
title: Anne Bione 
tagline: Tech Lead & PO
description: Cozinheira de chips e fios e grafiteira de kani. Tipicamente paulistana, mas do Recife.
paginate: 5
