excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://annebione.github.io
title: Anne Bione 
tagline: A log of everyday life
description: Front-end, UX, Javascript and eveything that comes with it.
paginate: 5
