excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://annebione.github.io
title: Anne Bione 
tagline: Engenharia de software. UX. JavaScript. Projetos. Política.
description: Engenharia de software. UX. JavaScript. Projetos. Política.
paginate: 5
