excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://annebione.github.io
title: Anne Bione 
tagline: Front-end, UX, Javascript and eveything that comes with it.
description: Front-end, UX, Javascript and eveything that comes with it.
paginate: 5
